### PR TITLE
Astropy modeling [WIP]

### PR DESCRIPTION
**Pull request by eblur**
Title: Fitting data with astropy.modeling

**What are the learning goals?**
astroquery
Astropy.modeling
Learn how to use matplotlib.pyplot.scatter and play with parameters
Learn how to make matplotlib.pyplot.errorbar and play with parameters
Learn how to write a function with a formatted doc string
Defining your own fit statistic
Scipy optimization 
Combine astropy models (e.g. a line plus a gaussian)

**Challenge problems**
Making a fake dataset with noise
Fit with emcee
Write your own mcmc
Write your own polynomials [using emcee]
Confidence intervals

### CODE REVIEW

**Comment by kelle** [comment]
here's a very relevant notebook which demonstrates lots of the functionality we want to to include in this tutorial: https://github.com/spacetelescope/aas229_workshop/blob/master/Lecture_Notebooks/modeling/aas229_Modeling.ipynb

**Comment by alouisew** [comment]
Additional planning notes for the tutorial can be found in this google doc: https://docs.google.com/document/d/1eQCsHNDh4m9uZrbYLabaNUIIthH7JQUVXcOwhbPnIlk/edit?usp=sharing

**Comment by chareepeters** [comment]
I'm also working on this! :D

**Comment by eblur** [comment]
We are working on pulling in more information from @adrn's tutorial https://github.com/adrn/PrincetonStatsSeminar/blob/master/notebooks/Fitting%20a%20straight%20line%20to%20data%20-%20lecture%20notes.ipynb

**Comment by alouisew** [comment]
To do list:
[] Replace our filter with np.all
[] Add plot of model fitting results
[] Write fitting narrative
[] Links to literature: stats book, blah blah
[] Hyperlinks to guides
[] Fill in "make your own stat"
[] Move simulating data to new section
[] Add learning goals, authors, and description to heading
[] Edit section headings

**Comment by eblur** [comment]
- [ ] Add challenge questions

**Comment by adrn** [comment]
Hey @eblur! Should we close this in preparation for @rkiman's work this summer, or do you want to pick this up?

**Comment by eblur** [comment]
Closing this due to effort by @rkiman

**Pull request closed without merging**
