### PR TITLE
Fix bug in color-excess.ipynb

### LINKED ISSUE #481: color-excess tutorial is failing
See, e.g., https://app.circleci.com/pipelines/github/astropy/astropy-tutorials/106/workflows/16a549a0-38a4-4356-b1c2-d9688590e408/jobs/791

### PR DESCRIPTION
**Pull request by krislars**
Changed astroquery.mast observation id

EDIT: Fix #481

### CODE REVIEW

**Comment by krislars** [comment]
Should fix issue #481

**Comment by adrn** [comment]
Thanks for this!

(and...why aren't the checks running?!)

**Comment by pllim** [comment]
*Organizations on our free plan get 400,000 free credits per month ($2,880 annual value) to use for Linux open source builds. Enabling this will allow this project’s builds to use them and let others see your builds, both through the web UI and the API.*

Did you hit the quota? I don't know how to check. https://app.circleci.com/pipelines/github/astropy/astropy-tutorials

**Comment by adrn** [comment]
I don't have permissions for astropy's circleci, so I can't tell either. Well, I'm going to #yolo this PR in, then, and test locally!

**Comment by adrn** [comment]
Thanks @krislars - hopefully this fixes the failure 😅

**Pull request merged**
