### PR TITLE
Making 'isophote' a sub package of 'photutils'

### PR DESCRIPTION
**Pull request by ibusko**
Moved and fixed the three tutorials to astropy-tutorials. 

The remote data ingestion feature (as explained in the CONTRIBUTING.md file) doesn't seem to work, so the data files are for now pinned on the same directories with the notebook files.

### CODE REVIEW

**Comment by pllim** [comment]
c/c @larrybradley , @saraogaz

**Comment by larrybradley** [comment]
These could also go in https://github.com/astropy/photutils-datasets

**Comment by ibusko** [comment]
Added a missing data file.

**Comment by adrn** [comment]
Sorry for losing track of this! These are useful examples, but a little shorter than we are thinking for tutorials, so I'm going to close this. Feel free to re-open this PR if you are still interested in working on this and would want to lengthen the examples a bit. Thanks!

**Pull request closed without merging**
