### PR TITLE
Synthetic images [WIP]

### PR DESCRIPTION
**Pull request by yihaochen**
**Learning Goals:**
- Assign WCS astrometry to an image using ```astropy.wcs``` 
- Construct a PSF using ```astropy.modeling.model```
- Convolve raw data with PSF using ```astropy.convolution```
- Calculate polarization fraction and angle from Stokes I, Q, U data
- Overplot quivers on the image

**Keywords**
astrometry, WCS, fits image, fits Header, polarization, radio, stokes parameters, PSF, convolution, quiver plot, visualization

**Steps**
1. Load and examine the FITS file
2. Set up astrometry coordinates
3. Prepare a Point Spread Function (PSF))
3.a How to do this without astropy kernels
4. Convolve image with PSF
5. Exercise: add some noise to the data
6. Convolve Stokes Q and U images
7. Calculate polarization angle and fraction for quiver plot

### CODE REVIEW

**Comment by bsipocz** [comment]
(If the goal here is to use fully syntetic images then one could also use the tools in http://photutils.readthedocs.io/en/stable/photutils/datasets.html, they are named ``make_***``. However if the simulation is not part of this tutorial, then I consider renaming it as the process should not be different when using simulated or observed data both stored in fits files. )

**Comment by heinzs57** [comment]
We have been working on adding astrometry to simulation output files of stoke intensities. We implemented PSF convolution to simulate more realistic synthetic observations. We displayed the images with proper coordinate axes. We added documentation and wording to the tutorial for each step. The google doc with learning goals and outline is located at

https://docs.google.com/document/d/1VrtxuBjWbhAhlPxZliEJ8HsQO83aUprunDrJ_ghKcMk/edit

**Comment by bsipocz** [comment]
Sure, my point is that maybe a different title would better describe the full content of the tutorial, as most of the steps could very well applied for observed images, and I would not necessarily look for them in a tutorial that's called "syntetic images".

**Comment by eblur** [comment]
- Remove the "Adding Noise" section
- Use `download_file` to fetch the data (instead of hyperlinks)

**Comment by eblur** [comment]
Resubmitted in PR #179

**Pull request closed without merging**
