### PR TITLE
fix wcs bug in UVES.ipnyb

### PR DESCRIPTION
**Pull request by emilurice**
changed wcs = WCS(header) to wcs = wcs.WCS(header) - I think this fixes Issue #206: https://github.com/astropy/astropy-tutorials/issues/206

### CODE REVIEW

**Comment by emilurice** [comment]
Oops the change also has to be mane in the `def read_spec(filename):` block

**Comment by emilurice** [comment]
I changed the second instance! I am slowly relearning github. :) Should be really fixed now.

**Comment by bsipocz** [comment]
@emilurice - Where did you run into that `NameError`? 
`WCS` seem to be imported at the top of the notebook (in line 151), and this suggested workaround won't work for various reasons: `wcs` is not imported, and either way you would override it in the first change.

**Comment by emilurice** [comment]
@bsipocz Hmmm, I guess I didn't understand the difference between WCS & wcs, and I might not have been using the most updated astropy. I just checked again and did not get the same NameError.

**Pull request closed without merging**
