### PR TITLE
New tutorial User defined model

### PR DESCRIPTION
**Pull request by rkiman**

### CODE REVIEW

**Comment by adrn** [comment]
Rendered version here: https://circleci.com/gh/astropy/astropy-tutorials/117/artifacts/0/home/circleci/project/build/html/index.html

**Comment by rkiman** [comment]
Hi @adrn, could you explain me what rendered version means? And also, I couldn't open that link. Thanks!

**Comment by eblur** [comment]
I sent an email to Nadia, Tom R, and Perry G with a request to review.

**Comment by nden** [comment]
I will ignore spelling/grammar issues unless you want me to comment on them.

The code looks good in general. A minor comment I have is about the name of the new class. To follow PEP8 this should be `class SineNew` instead of `class sine_new`.

Also, if possible, as good practice, specify some sensible default values for the parameters. These are not required so if you choose to do so you can add a comment about that.

Other than that it looks good.

**Comment by rkiman** [comment]
@nden thank you for your comments. Could you give me one example for the comments about the default values?
Thank you.

**Comment by nden** [comment]
@rkiman For example, the defaults can be 

```
a = Parameter(default=1)
b = Parameter(default=1)
c = Parameter(default=0)
d = Parameter(default=0)
```
This allows one to initialize the model without parameters, e.g.
```
m = SineNew()
```

**Comment by rkiman** [comment]
Great. Thank you.

**Pull request merged**
