### PR TITLE
Test gh pages

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by adrn** [comment]
Can you rebase and remove your edits to the circleci config?

**Comment by Cadair** [comment]
Done :)

On 8 December 2018 10:55:08 GMT-07:00, Adrian Price-Whelan <notifications@github.com> wrote:
>Can you rebase and remove your edits to the circleci config?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/astropy/astropy-tutorials/pull/294#issuecomment-445477449

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adrn** [comment]
I've wasted way too much time trying to debug readthedocs - for now, I think it's much more critical to have a working website, so I'm going to merge this and will make sure that the gh-pages site looks ok before pinging @eteq to switch the DNS record.

**Comment by adrn** [comment]
Thanks @Cadair!

**Pull request merged**
