### PR TITLE
TST: Remove Travis

### LINKED ISSUE #467: TST: Use GitHub Actions
Please see https://groups.google.com/g/astropy-dev/c/45frnTEAX-U

### PR DESCRIPTION
**Pull request by pllim**
Close #467 

@kakirastern said Travis isn't used anyway? If it does, you can close this without merge and open a new PR to do the port to Actions.

### CODE REVIEW

**Comment by pllim** [comment]
CircleCI failure unrelated.

**Comment by kakirastern** [comment]
Strange, it's a `KeyError`:
```
KeyErrorTraceback (most recent call last)
<ipython-input-14-3cb6373bfea7> in <module>
      1 # Query for Herschel data in a 1 degree radius around the SMC
----> 2 result = ESASky.query_region_maps('SMC', radius=1*u.deg, missions='Herschel')
      3 
      4 print(result)

~/project/venv/lib/python3.7/site-packages/astroquery/esasky/core.py in query_region_maps(self, position, radius, missions, get_query_payload, cache)
    236         self._store_query_result_maps(query_result, sanitized_missions,
    237                                       coordinates, sanitized_radius,
--> 238                                       get_query_payload, cache)
    239 
    240         if (get_query_payload):

~/project/venv/lib/python3.7/site-packages/astroquery/esasky/core.py in _store_query_result_maps(self, query_result, missions, coordinates, radius, get_query_payload, cache)
    768             mission_table = self._query_region_maps(coordinates, radius,
    769                                                     mission, get_query_payload,
--> 770                                                     cache)
    771             if (len(mission_table) > 0):
    772                 query_result[mission.upper()] = mission_table

~/project/venv/lib/python3.7/site-packages/astroquery/esasky/core.py in _query_region_maps(self, coordinates, radius, observation_name, get_query_payload, cache)
    682         query = (
    683             self._build_observation_query(coordinates, radius,
--> 684                                           self._find_observation_parameters(observation_tap_name)))
    685         request_payload = self._create_request_payload(query)
    686         if (get_query_payload):

~/project/venv/lib/python3.7/site-packages/astroquery/esasky/core.py in _build_observation_query(self, coordinates, radius, json)
    711         from_query = " FROM {}".format(json[self.__TAP_TABLE_STRING])
    712         if (radiusDeg != 0 or json[self.__IS_SURVEY_MISSION_STRING]):
--> 713             if (json[self.__IS_SURVEY_MISSION_STRING]):
    714                 where_query = (" WHERE 1=CONTAINS(pos, CIRCLE('ICRS', {}, {}, {}));".
    715                                format(ra, dec, radiusDeg))

KeyError: 'isSurveyMission'
KeyError: 'isSurveyMission'
```

**Comment by kakirastern** [comment]
On the `astroquery` side too

**Comment by kakirastern** [comment]
Think I may need to make a patch at `astroquery` or open an issue there at least...

**Comment by kakirastern** [comment]
Definitely not a server-side issue (but a syntax issue).

**Comment by adrn** [comment]
For the failing build, see #463 and #470

**Comment by adrn** [comment]
Thanks @pllim

**Pull request merged**
