### PR TITLE
Try and add filter search warning when no results is returned

### LINKED ISSUE #337: Sometimes the tutorials don't load when going to main tutorials page
About 50% of the time, when I go to learn.astropy.org and click "tutorials," the page says "No tutorials found!" until I refresh, and then the tutorials appear. I know @eblur and @kelle have run in to this issue as well. Do you have any idea what could be causing this? I think this is the highest priority bug to work on in the near term!

### PR DESCRIPTION
**Pull request by kakirastern**
To follow up on PR #340. To try and find a way to add back filter search warning when no tutorials are returned on a filter search. 

Fixes #337.

### CODE REVIEW

**Comment by kakirastern** [comment]
Testing if `$.ajax()`-related latency issues are the root cause of the 1st-time-load-tutorials bug...

**Comment by kakirastern** [comment]
Yes, @MananAgarwal was right, it is indeed a latency issue. I have corrected for it by adding the option `async: false` to the two instances of JQuery `$.ajax()`in the file "searchtools.js". Think it is fixed now. Please check @MananAgarwal and @adrn. Thanks!

**Comment by kakirastern** [comment]
Wait... seems like the same problem is cropping up on my other browser. Let me double check.

**Comment by kakirastern** [comment]
I discovered the behavior is browser dependent too. Will need to work on it more before we meet next Tuesday and see if there is a way around it...

**Comment by kakirastern** [comment]
So for my Safari, I see this on my screen:

screenshot 2019-03-06 13 54 15

I don't get this with Chrome, which is more like:

screenshot 2019-03-06 13 56 35

**Comment by kakirastern** [comment]
I can confirm that the fix works only for Chrome, but not Firefox nor Safari... 🙁

**Comment by kakirastern** [comment]
But I reckon there must be another way to do this... Will need to experiment and investigate some more, but it will take time

**Comment by kakirastern** [comment]
@MananAgarwal I found this post and think it might be relevant for finding a solution to our current problem... [https://stackoverflow.com/a/28862458/9959073](https://stackoverflow.com/a/28862458/9959073). So a potential solution would be implement something like
```
if(!tbody.find('td').hasClass(settings.highlightClass)) {
    $('body').find('#empty').text('No results').show();
} else {
    $('body').find('#empty').hide();
}
```
together with
```
...
</table>
<p id="empty"></p>
</body>
```
Except in their case it is for jQuery.FilterTable to return an alert when no results found... I am not sure if it will work for the current code base though. What do you think?

**Comment by kakirastern** [comment]
Or this one here might work: [https://stackoverflow.com/a/14340948/9959073](https://stackoverflow.com/a/14340948/9959073)...

**Comment by kakirastern** [comment]
I just attempted another fix so that the code now works for both Google Chrome and Mozilla Firefox browsers, and the 1st-time-load error no longer bugs these two kinds of browsers. What I did was to add `jQuery.ajaxSetup({async:false});` to the very beginning of the file "tutorials/themes/tutorials-theme/static/searchtools.js", to make sure that ajaxSetup is set to synchronous to make all $.get and $.ajax calls synchronous, which could be in bad form in some other context for some other JS file. 

I am not sure what is going wrong with the Apple Safari browser... Maybe if we merge this code a warning about this sit being optimized for both Chrome and Firefox would be necessary.

**Comment by MananAgarwal** [comment]
Hey @kakirastern, it is working for me on chrome, so I think we are on the right track to figuring this out. I am a little preoccupied with my midterm exams. I'll look into this properly on the weekend.

**Comment by kakirastern** [comment]
No worries @MananAgarwal! I have checked the the latest solution sometimes work on my Firefox browser, and sometimes it does not... Anyway, we can discuss later. All the best with your midterm exams!

**Comment by adrn** [comment]
Ah, great! This works for me locally too. Why do you say it doesn't work on Firefox or Safari? It seems to work for me on all browsers.

**Comment by adrn** [comment]
Thanks for this - given that it solves the issue for at least Chrome and Safari, I'm going to merge and we can discuss whether or not it works for all browsers over in #337

**Comment by kakirastern** [comment]
Hi @adrn! It's weird. I checked the `giles` version via incognito mode using both Firefox and Safari and it wasn't working. Let me check again now the PR's been merged. Wait... (may take a while).

**Pull request merged**
