### PR TITLE
Improved responsiveness

### PR DESCRIPTION
**Pull request by MananAgarwal**
Resolves issue #295

### CODE REVIEW

**Comment by MananAgarwal** [comment]
Travis build is failing due to some nbconvert related issue.

**Comment by pllim** [comment]
Yeah, not sure why `nu18` is claimed to be undefined as it was defined in a previous cell in https://github.com/astropy/astropy-tutorials/blob/master/tutorials/notebooks/quantities/quantities.ipynb . I restarted the build in case it is a transient problem.

**Comment by adrn** [comment]
Yea, ignore the travis failure - we need to figure out a better solution for travis testing because this timeout happens a lot...

**Comment by adrn** [comment]
Thanks @MananAgarwal - this does look to me like it fixes #295

**Pull request merged**
