### PR TITLE
New tutorial Models-Quick-Fit

### PR DESCRIPTION
**Pull request by rkiman**

### CODE REVIEW

**Comment by rkiman** [comment]
I can't see the notebook in GitHub. Neither in my repository [here](https://github.com/rkiman/Tutorials/blob/master/Models-Quick-Fit/Models-Quick-Fit.ipynb)

**Comment by adrn** [comment]
Could you rebase this PR? It looks like this is based on an old version of the repo that wasn't set up to build on circleci (hence why that build is failing). If you rebase, it should produce a live demo of the new tutorial for us to take a look at. I'll message you on slack to help with the rebase.

**Comment by nden** [comment]
@eblur asked me to look at the notebook for  accuracy. It looks good to me. Thanks for writing it!

**Comment by rkiman** [comment]
Making a new pull request after rebase

**Comment by adrn** [comment]
Note: this is because this PR is based on the master branch of Rocio's fork, and we moved the changes over to a separate branch. See #242

**Pull request closed without merging**
