### PR TITLE
Fix bugs in the "vo" tutorial

### LINKED ISSUE #427: Failures in conesearch tutorial
It looks like some behavior has changed with conesearch - would you mind updating the tutorial @pllim?

e.g., https://circleci.com/gh/astropy/astropy-tutorials/686

### PR DESCRIPTION
**Pull request by kakirastern**
Update outdated code, as well as added required package version to `requirements.txt` file for better version control. 

Fixes #427. 
Addresses #428.

### CODE REVIEW

**Comment by pllim** [comment]
Sorry for the duplicated effort, @kakirastern , but by the time I saw this, I was already finished with #430 .

**Comment by kakirastern** [comment]
@pllim Wow, what a coincidence! Not a problem, I will let @adrn decide what to do with the duplicated efforts next...

**Comment by kakirastern** [comment]
```
INFO: Processing notebook conesearch.ipynb (in /home/circleci/project/tutorials/notebooks/vo) [convert]

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/circleci/project/venv/lib/python3.7/site-packages/sphinx/config.py", line 348, in eval_config_file
    execfile_(filename, namespace)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/circleci/project/tutorials/conf.py", line 164, in <module>
    process_notebooks(nb_tutorials_path, **processkwargs)
  File "/home/circleci/project/scripts/convert.py", line 238, in process_notebooks
    nbc.execute()
  File "/home/circleci/project/scripts/convert.py", line 97, in execute
    executor.preprocess(nb, {'metadata': {'path': self.path_only}})
  File "/home/circleci/project/venv/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 403, in preprocess
    with self.setup_preprocessor(nb, resources, km=km):
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 345, in setup_preprocessor
    self.km, self.kc = self.start_new_kernel(**kwargs)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 291, in start_new_kernel
    km.start_kernel(extra_arguments=self.extra_arguments, **kwargs)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/jupyter_client/manager.py", line 246, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/home/circleci/project/venv/lib/python3.7/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 236, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named astro

make: *** [Makefile:43: html] Error 2

Exited with code exit status 2
```

**Comment by pllim** [comment]
There is no need to work on this more until we hear back from @adrn , *but* if this one is the winner, you need to clear the output (and squash out the commits) and remove exact pinning.

**Comment by kakirastern** [comment]
Okay, sure. No problem.

**Comment by adrn** [comment]
Thanks @kakirastern! This looks pretty equivalent to @pllim's changes, but she has already cleared output, so for the sake of simplicity I'll just merge her PR. Thanks very much for jumping on this and sorry for instigating duplicate effort!

**Comment by kakirastern** [comment]
@adrn No worries, I did learn a lot from the experience

**Comment by adrn** [comment]
Great! In the future, feel free to leave a comment in an issue that you are working on something - for example, you could have left a comment in #427 mentioning that you were working on a PR. It's something I often forget to do as well :) Thanks again for the PR!

**Comment by pllim** [comment]
> I did learn a lot from the experience

Hopefully good things. I apologize for any inconvenience caused! :sweat_smile:

**Pull request closed without merging**
