### PR TITLE
Better header

### LINKED ISSUE #197: Move the content of the "green box" tutorial header Note to menu bar
We're planning to have a standard, stylized header / introduction at the start of each notebook. @eblur and I discussed that the current green "note" about Binder could move to make more screen real estate for the new headers. In principle, we could just add two links to the menu bar: "Download" and "Interactive notebook" rather than the current `.. Note::`.

### PR DESCRIPTION
**Pull request by adrn**
Fixes #197 

This identifies any markdown cell that starts with "# Introduction" and re-styles it to have a blue background. The particular string "# Introduction" could be anything, or could even be in the cell metadata.

Also, the style I chose was just to show off that we can control it with CSS, so feel free to suggest other ideas! 

image

### CODE REVIEW

**Comment by eblur** [comment]
Most of our standardized headers start with the title and then give supporting info (e.g. Authors).  So the identifier could be any cell that starts with "## Author"

The question that remains:
Should the title appear before or after the blue box?

@kelle @eteq please comment on this implementation

**Comment by eblur** [comment]
one more comment @adrn 

The "Download tutorial notebook" and "Interactive tutorial notebook" links seem easy to miss. Can we give them buttons or insert them somewhere else that makes them more obvious?

**Comment by kelle** [comment]
If possible,
Title first.
followed by Authors, then Introduction.

I agree that the links/buttons to download and run the tutorial should be more visible...possibly right under the title.
I also think those links/button should be repeated at the bottom of the notebook.

**Comment by adrn** [comment]
After thinking about this a bit more, now I like:
* __Big, bold__: Title
* __Formatted as a normal markdown cell__: authors, keywords , learning goals
* __Formatted differently__ (e.g. with a blue background): Standard setup instructions / intro that should appear on every tutorial (short instructions on how to download, setup, and run locally)
 Title / author / 
* __Normal cell formatting__: tutorial content

So, this would just amount to injecting the standard setup instructions into the rendered pages where relevant.

**Comment by eblur** [comment]
@adrn I like the way you are thinking. However, most of our content doesn't follow that format. It requires putting each piece in a separate cell, correct?

How about for now:
1. Put the Title before the blue box
2. Put the "authors" and all supporting content in the blue box
3. Modify our contributing.rst to ensure that authors put the title and supporting info into separate cells

For later:
We should make a template tutorial file with the header format you suggested above. Once we provide the template, we will (hopefully) populate the website with new and better content. With a critical mass of uniform template styles, we can modify the website style, and also bring the old tutorials up to date with the new header format.

Sound good?

**Comment by kelle** [comment]
that plan sounds good to me.

**Comment by adrn** [comment]
FYI: I descoped this PR drastically to just include better buttons for downloading / going to the interactive tutorial on binder. Will address other matters in other PRs...

**Pull request merged**
