### PR TITLE
fix use of weights in fitting tutorial

### PR DESCRIPTION
**Pull request by keatonb**
- [ X] Check the box to confirm that you are familiar with the [contributing guidelines](https://learn.astropy.org/contributing/how-to-contribute) and/or indicate (check the box) that you are familiar with our contributing workflow.
- [X ] Confirm that any contributed tutorials contain a complete Introduction which includes an Author list, Learning Goals, Keywords, Companion Content (if applicable), and a Summary.
- [ X] Check the box to confirm that you are familiar with the Astropy community [code of conduct](https://github.com/astropy/astropy/blob/main/CODE_OF_CONDUCT.md) and you agree to follow the CoC.

I changed all instances of `weights = 1.0/error**2` to `weights = 1.0/error` to address #570.

### CODE REVIEW

**Review by adrn — APPROVED** [review]
Thanks for catching this! Tagging @rkiman in case she wants to have a look

**Comment by rkiman** [comment]
Thank you for catching this! I would just modify your note "Note that the fitting routine takes weights as 1/error and squares them for you, which is different from the definition of weights used on the linked pages." to: Note that the fitting routine takes weights as 1/error and squares them for you, as indicated in the description of the function (and add the link, even though it is indicated in other parts of the tutorial).

**Comment by keatonb** [comment]
I made the change you suggested @rkiman.  Cheers!

**Comment by adrn** [comment]
Thanks @keatonb and @rkiman !

**Pull request merged**
