### PR TITLE
Add updates to tutorials from PyAstro19

### PR DESCRIPTION
**Pull request by stephtdouglas**
As part of the response to #281, here are updates for 10 of the current tutorials. I've assigned/edited keywords for all of these tutorials, and also updated titles, learning goals, and main text where needed.

### CODE REVIEW

**Comment by eblur** [comment]
The tests appear to be failing on the UVES tutorial, which you did not modify. I tested the UVES tutorial on my local machine (running Astropy 3.1.1) and did not get an error. I've posted a message to the #units channel in Slack to see if this is a known issue.

**Comment by kelle** [comment]
@eblur , should @stephtdouglas  move UVES into a quarantine folder?

**Comment by adrn** [comment]
I just rebased this on my branch, which should fix the unrelated circleci failures.

**Comment by adrn** [comment]
Thanks @stephtdouglas !!

**Pull request merged**
