### PR TITLE
WIP New tutorial: spectroscopic data reduction

### PR DESCRIPTION
**Pull request by keflavich**
I've written a 3-part tutorial:

(1) Spectroscopic Tracing
(2) Wavelength Calibration
(3) Put it together and calculate the EQW

The data set is included in the form of 5 .bmp files (bitmap), since apparently these spectra were taken by a camera that spits out that format.  The total size is too big  - each .bmp is 1.6 MB. 

These were written as lecture material for a class targeted at senior undergraduates (analogous to [Stuart Littlefair's PHY217](http://slittlefair.staff.shef.ac.uk/teaching/phy217/)).  It therefore includes some additional analysis that isn't strictly necessary for a technical tutorial.

The wavelength catalog selection using NIST data reveals some flaws in the astroquery interface, but they're simple enough to overcome so I haven't raised an issue yet... NIST tables are just not meant to be machine-read.

TODO before merging:
* [ ] re-host data on astropy-data or somewhere else
* [ ] add data retrieval to notebooks

### CODE REVIEW

**Comment by keflavich** [comment]
I can't guarantee I'll be able to finish this in finite time, so I would strongly encourage someone else to take over - this might be a good exercise for a new participant in the astropy community who is interested in spectroscopy.

**Comment by keflavich** [comment]
Run versions here: https://github.com/keflavich/AST4723-Public-Materials/tree/master/spectroscopy

**Comment by pllim** [comment]
I thought you have a whole class of students to help you. 😉

**Comment by keflavich** [comment]
My students are great, but they're not generally trained in programming.

**Comment by pllim** [comment]
Gotta start somewhere! 😸

**Comment by keflavich** [comment]
https://colab.research.google.com/github/keflavich/AST4723-Public-Materials/blob/master/spectroscopy/Spectroscopic%20Trace%20Tutorial.ipynb
https://colab.research.google.com/github/keflavich/AST4723-Public-Materials/blob/master/spectroscopy/Wavelength%20Calibration.ipynb

**Pull request closed without merging**
