### PR TITLE
Add "Spectrum Plot" tutorial to Learn Astropy repo

### LINKED ISSUE #331: New Tutorial: Turning jmangum/spectrumplot into Learn Astropy tutorial
The concerned repo is for using Astropy and affiliated packages to make a publication-quality spectrum with labeled emission lines through a cube. I am proposing to turn the GitHub repo at [https://github.com/jmangum/spectrumplot/blob/master/CubeSpectrumPlotExample.rst](https://github.com/jmangum/spectrumplot/blob/master/CubeSpectrumPlotExample.rst) into a proper Learn Astropy tutorial. Have already sought original repo owner's written permission and have tested out the code myself successfully, with the reproduced image attached. So next stage is to turn the existing Python code into a tutorial format before moving on to the proofreading/editing stage. 

spectrum_try2

### PR DESCRIPTION
**Pull request by kakirastern**
Fixes #331.

Adding new content to the Learn Astropy repo as the "Spectrum Plot" tutorial originally authored by Jeff Mangum. Original source can be accessed at: https://github.com/jmangum/spectrumplot. Consent has been obtained from Mangum to use his original material. This version is an expanded version of the original. Previously tested on Google Colab and the tutorial has been running successfully.

### CODE REVIEW

**Comment by kakirastern** [comment]
May need to add `requirements.txt` to the new `spectrumplot` directory containing the tutorial material including the Jupyter notebook. Once that has been done will remove the `[WIP]` tag from the PR heading.

**Comment by kakirastern** [comment]
Google Colab link: https://drive.google.com/file/d/1MEW9J3o-Mpryd84gvO2tvvPaTdYsvdIf/view?usp=sharing

**Comment by kakirastern** [comment]
Am testing the setup tonight but unfortunately is not in form so kept making minor mistakes... Once the PR passes the CircleCI tests will then rebase and squash all commits into one.

**Comment by kakirastern** [comment]
My apologies for the many CircleCI failures. This tutorial works locally but for some reason needs much effort to get it to work on Learn Astropy as well. Will try smarter instead of harder from now on.

**Comment by kakirastern** [comment]
```
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/circleci/project/venv/lib/python3.7/site-packages/nbformat/reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 311 column 32 (char 11034)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/project/venv/lib/python3.7/site-packages/sphinx/config.py", line 348, in eval_config_file
    execfile_(filename, namespace)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/circleci/project/tutorials/conf.py", line 164, in <module>
    process_notebooks(nb_tutorials_path, **processkwargs)
  File "/home/circleci/project/scripts/convert.py", line 238, in process_notebooks
    nbc.execute()
  File "/home/circleci/project/scripts/convert.py", line 94, in execute
    nb = nbformat.read(f, as_version=IPYTHON_VERSION)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/nbformat/__init__.py", line 140, in read
    return reads(fp.read(), as_version, **kwargs)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/nbformat/__init__.py", line 73, in reads
    nb = reader.reads(s, **kwargs)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/nbformat/reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/nbformat/reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: '{\n "cells": [\n  {\n   "cell_type": "m...

make: *** [Makefile:43: html] Error 2

Exited with code exit status 2
```

**Comment by kakirastern** [comment]
TODO: Will need to move cube file to http://data.astropy.org server to make things work, as suggested in http://learn.astropy.org/contributing.html#data-files. Planning to do so next.

**Comment by kakirastern** [comment]
Moving additional contents, including the data cube FITS file, to https://github.com/astropy/astropy-data/ via PR https://github.com/astropy/astropy-data/pull/86. Will need to follow up soon before this PR can be finalized.

**Comment by kakirastern** [comment]
Now am getting the expected 404 error. Will try to resolve this during one of the upcoming telecons soon.

**Comment by bsipocz** [comment]
this needs a review from the @astropy/learn-astropy-maintainers team before I'm comfortable to merge the fits file into astropy-data

**Comment by kakirastern** [comment]
@bsipocz Thanks for the notice! I will follow the matter up during one of the upcoming Learn Astropy telecons so that the maintainers will be aware of the situation and will review this PR accordingly.

**Comment by eblur** [comment]
I've reviewed approximately half of the notebook in detail. At this moment, it needs much more exposition and explanation of what is going to be done in the notebook and why. I've made a lot of notes for places were more explanatory material needs to be.

However, I am concerned that several of the packages used in this tutorial are in the actively process of being replaced by specutils in some way. I recommend that we clean, perhaps rewrite, this tutorial during the Astropy spectroscopy sprint to make it as up-to-date with the Astropy ecosystem as possible.

**Comment by kakirastern** [comment]
> I've reviewed approximately half of the notebook in detail. At this moment, it needs much more exposition and explanation of what is going to be done in the notebook and why. I've made a lot of notes for places were more explanatory material needs to be.
> 
> However, I am concerned that several of the packages used in this tutorial are in the actively process of being replaced by specutils in some way. I recommend that we clean, perhaps rewrite, this tutorial during the Astropy spectroscopy sprint to make it as up-to-date with the Astropy ecosystem as possible.

Sure, can do more exposition and explanation with a rewrite during Spectroscopy Sprint 2020 this week.

**Comment by kakirastern** [comment]
@eblur I kind of get the idea of how you would like this tutorial to go, and will rewrite the tutorial significantly to match with your expectations.

**Comment by kakirastern** [comment]
@eblur @kelle and @stargaser The Colab version of the 1st WCS tutorial is ready for another (possibly a final) review: https://colab.research.google.com/drive/14ZN73gO9aIiqX-bd8PsXuBxGspO-6eOQ?usp=sharing

**Comment by kakirastern** [comment]
Will move onto Git from Colab once latest changes have been approved (especially by @eblur).

**Pull request closed without merging**
