### PR TITLE
Add a Units tutorial

### PR DESCRIPTION
**Pull request by keflavich**
I think this is the first thing I want to teach folks here; it's super easy to use and incredibly useful on a daily basis.

I'd appreciate feedback - @kelle, a checklist for important things to add would be great.  Probably the starting place should be the astropy docs.  Right now the units demo isn't much different from the docs.  

@adrn, I think you had an equivalent notebook at some point?  Perhaps we should merge these?  Or just use yours?

### CODE REVIEW

**Comment by hamogu** [comment]
Any progress on this since April 2014? Or is this not needed any longer and the PR can be closed?

**Comment by eteq** [comment]
@hamogu raised a good question here.  @keflavich, what do you think?  The obvious comparison is #51, which is a pretty thorough treatment of quantities.  Do you think this has more that should still be included, or should we just close this one?

**Comment by hamogu** [comment]
Quantities are also used as an example in other notebooks, e.g. see "Units and constants in astropy" in http://www.astropy.org/astropy-tutorials/UVES.html

**Comment by keflavich** [comment]
Let's drop it, then, and I'll add to the other tutorials as needed.

**Pull request closed without merging**
