### PR TITLE
Make tutorial headers more uniform

### LINKED ISSUE #239: Make current tutorial headers uniform
The current tutorials have different header formats. Change the jupyter notebooks to conform to template intro in [Contributing.md](http://astropy-tutorials.readthedocs.io/en/latest/contributing.html#contributing-page)

### PR DESCRIPTION
**Pull request by adrn**
This is a first stab at making the tutorial headers (i.e. the first markdown cell in each notebook) more uniform across the tutorials. We need this for #247 so that each notebook specifies a set of keywords. I tried to add summaries where notebooks didn't have them, but many are missing learning goals. 

Could the authors please provide a set of learning goals (bulleted list of a few key takeaways) for:
* Viewing and manipulating FITS images (author @eblur)
* Viewing and manipulating FITS tables (author @eblur)
* Using Astropy Quantities for astrophysical calculations (authors Ana Bonaca, @eteq)
* Make a plot with both redshift and universe age axes using astropy.cosmology (author Neil Crighton)
* Analyzing UVES Spectroscopy with Astropy (@hamogu @migueldvb)
* VO Simple Cone Search Tutorial (@pllim)

This also then adds functionality for parsing out keywords from the newly uniform headers, and generates HTML meta tags from the keywords to be used in the javascript filtering functionality added in #247

This fixes #239

### CODE REVIEW

**Comment by adrn** [comment]
I had to fix an issue in `convert.py` to get the circleci builds working again. For some reason, the `ExecutePreprocessor` didn't like receiving 
`kernel_name = ExecutePreprocessor.kernel_name.default_value` if no kernel_name was specified...

**Comment by adrn** [comment]
Note: this includes the commits from #249

**Comment by kelle** [comment]
I think it's fine to leave those without learning goals as "To Do", merge this PR, and then make a new issue with the Notebooks needing the learning goals.

**Comment by kelle** [comment]
Here is the list of the current keywords:
https://docs.google.com/spreadsheets/d/1JmOF82Zmrs397wLwAmmL1rgDSsvP6Z4fLMr0hV5ZIb4/edit#gid=1529571570

Feel free to modify.

**Comment by kelle** [comment]
While we're working on this, I think we should make sure the science keywords are in the UAT (http://astrothesaurus.org/thesaurus/alphabetical-browse/ and http://astrothesaurus.org/thesaurus/autocomplete-widget/). 

E.g, "Physics" should be Stellar Physics. Dynamics should be Astrodynamics. 

I've made some changes to the keywords listed in the google sheet.

**Comment by adrn** [comment]
OK, merging this, but see #254!

**Pull request merged**
